#!/bin/sh
#
# Build with Jenkins CI.  This script is intended for use with the OME
# Jenkins CI infrastructure, though it may be useful as an example for
# how one might use various cmake options.
#
################################################################################

set -e

# Run build
build() {
    rm -rf "$builddir" "$installdir"
    mkdir -p "$builddir" "$installdir"

    (
        cd "$builddir"
        # Note that due to using a local git mirror, the ome-model-git-branch
        # is HEAD since it's already at the correct commit
        cmake \
            -G "$build_system" \
            -DCMAKE_VERBOSE_MAKEFILE:BOOL="$verbose" \
            -DCMAKE_BUILD_TYPE="$build_type" \
            -DCMAKE_INSTALL_PREFIX:PATH=${installdir} \
            ${sourcedir}

        # Build superbuild (and run tests)
        echo "Building everything"
        cmake --build .

        # Install
        echo "Installing"
        cmake --build . --target install
    )
}

test()
{
    install/bin/read-performance
}

workspace="$(/bin/pwd)"
sourcedir="${workspace}/source"
builddir="${workspace}/build"
installdir="${workspace}/install"
artefactdir="${workspace}/artefacts"
cachedir="${workspace}/cache"

build_type=Release
build_system="Unix Makefiles"
verbose=OFF
parallel=
parallel_opt=OFF

build
test
