#! /bin/sh
set -e
set -x

datapath="/fdata/rleigh/scratch/data"
binpath="/tmp/bm/src/main/cpp"
resultpath="${datapath}/results"
outpath="${datapath}/out"
iterations=10
imagesizex=16384
imagesizey=16384
bigimagesizex=65536
bigimagesizey=65536
tilesizestart=16
tilesizeend=2048
tilesizeincrement=16
stripsizestart=1
stripsizeend=256
stripsizeincrement=1
pixeltypes="uint8 int16 uint32 float"

# Clean results folder
mkdir -p "${resultpath}"
mkdir -p "${outpath}"
rm "${resultpath}"/* || echo "No results"
rm "${outpath}"/* || echo "No output"

# C++ tests
(
    for pixeltype in ${pixeltypes}; do
        "${binpath}/basic-tile-performance" ${iterations} \
                  ${imagesizex} ${imagesizey} \
                  tile ${tilesizestart} ${tilesizeend} ${tilesizeincrement} \
                  ${pixeltype} \
                  ${outpath}/tile-test-small \
                  "${resultpath}/tile-test-tile-small-${pixeltype}.tsv" \
                  "${resultpath}/tile-test-tile-small-${pixeltype}-sizes.tsv"
        rm -f "${outpath}"/*

        "${binpath}/basic-tile-performance" ${iterations} \
                  ${bigimagesizex} ${bigimagesizey} \
                  tile ${tilesizestart} ${tilesizeend} ${tilesizeincrement} \
                  ${pixeltype} \
                  ${outpath}/tile-test-big\
                  "${resultpath}/tile-test-tile-big-${pixeltype}.tsv" \
                  "${resultpath}/tile-test-tile-big-${pixeltype}-sizes.tsv"
        rm -f "${outpath}"/*

        "${binpath}/basic-tile-performance" ${iterations} \
                  ${imagesizex} ${imagesizey} \
                  strip ${stripsizestart} ${stripsizeend} ${stripsizeincrement} \
                  ${pixeltype} \
                  "${outpath}/strip-test.tiff" \
                  "${resultpath}/tile-test-strip-${pixeltype}.tsv" \
                  "${resultpath}/tile-test-strip-${pixeltype}-sizes.tsv"
        rm -f "${outpath}"/*
    done
)
