#! /bin/sh
set -e
set -x

for test in bbbc mitocheck tubhiswt; do
    input=unknown
    case "$test" in
        bbbc)
            input=${datapath}/BBBC/NIRHTa-001.ome.tiff
        ;;
        mitocheck)
            input=${datapath}/mitocheck/00001_01.ome.tiff
        ;;
        tubhiswt)
            input=${datapath}/tubhiswt-4D/tubhiswt_C0_TP0.ome.tif
        ;;
    esac

    # Java tests
    (
        mvn -P metadata -Dtest.iterations=${iterations} -Dtest.input="$input" -Dtest.output=${outpath}/${test}-java.ome.xml -Dtest.results=${resultpath}/${test}-metadata-linux-java.tsv exec:java
        for i in $(seq ${iterations}); do
            mvn -P metadata -Dtest.iterations=1 -Dtest.input="$input" -Dtest.output=${outpath}/${test}-java.ome.xml -Dtest.results=${resultpath}/${test}-metadata-linux-java-${i}.tsv exec:java
        done
    )

    # C++ tests
    (
        ${binpath}/metadata-performance ${iterations} "$input" ${outpath}/${test}-cpp.ome.xml ${resultpath}/${test}-metadata-linux-cpp.tsv
        for i in $(seq ${iterations}); do
            ${binpath}/metadata-performance 1 "$input" ${outpath}/${test}-cpp.ome.xml ${resultpath}/${test}-metadata-linux-cpp-${i}.tsv
        done
    )
done