#! /bin/sh
set -e
set -x

datapath="/data"
binpath="/install/bin"
resultpath="${datapath}/results"
outpath="${datapath}/out"
iterations=20
imagesizex=16384
imagesizey=16384
bigimagesizex=65536
bigimagesizey=65536
tilesizestart=16
tilesizeend=2048
tilesizeincrement=16
stripsizestart=1
stripsizeend=256
stripsizeincrement=1
pixeltypes="uint8 uint16 uint32 float double"

# Clean results folder
mkdir -p "${resultpath}"
mkdir -p "${outpath}"
rm "${resultpath}"/* || echo "No results"
rm "${outpath}"/* || echo "No output"

# C++ tests
(
    for pixeltype in ${pixeltypes}; do
        ${binpath}/tile-performance ${iterations} \
                  ${imagesizex} ${imagesizey} \
                  tile ${tilesizestart} ${tilesizeend} ${tilesizeincrement} \
                  ${pixeltype} \
                  ${outpath}/tile-test-small\
                  ${resultpath}/tile-test-tile-${pixeltype}.tsv

        ${binpath}/tile-performance ${iterations} \
                  ${bigimagesizex} ${bigimagesizey} \
                  tile ${tilesizestart} ${tilesizeend} ${tilesizeincrement} \
                  ${pixeltype} \
                  ${outpath}/tile-test-big\
                  ${resultpath}/tile-test-tile-${pixeltype}.tsv

        ${binpath}/tile-performance ${iterations} \
                  ${imagesizex} ${imagesizey} \
                  strip ${stripsizestart} ${stripsizeend} ${stripsizeincrement} \
                  ${pixeltype} \
                  ${outpath}/strip-test.tiff \
                  ${resultpath}/tile-test-strip-${pixeltype}.tsv
    done
)
