#! /bin/sh
set -e
set -x

for test in bbbc mitocheck tubhiswt; do
    input=unknown
    case "$test" in
        bbbc)
            input=${datapath}/BBBC/NIRHTa-001.ome.tiff
        ;;
        mitocheck)
            input=${datapath}/mitocheck/00001_01.ome.tiff
        ;;
        tubhiswt)
            input=${datapath}/tubhiswt-4D/tubhiswt_C0_TP0.ome.tif
        ;;
    esac

    # Java tests
    (
        mvn -P pixels -Dtest.iterations=${iterations} -Dtest.input="$input" -Dtest.output=${outpath}/${test}-java.ome.tiff -Dtest.results=${resultpath}/${test}-pixeldata-linux-java.tsv exec:java
        for i in $(seq ${iterations}); do
            mvn -P pixels -Dtest.iterations=1 -Dtest.input="$input" -Dtest.output=${outpath}/${test}-java.ome.tiff -Dtest.results=${resultpath}/${test}-pixeldata-linux-java-${i}.tsv exec:java
        done
    )

    # C++ tests
    (
        ${binpath}/pixels-performance ${iterations} "$input" ${outpath}/${test}-cpp.ome.tiff ${resultpath}/${test}-pixeldata-linux-cpp.tsv
        for i in $(seq ${iterations}); do
            ${binpath}/pixels-performance 1 "$input" ${outpath}/${test}-cpp.ome.tiff ${resultpath}/${test}-pixeldata-linux-cpp-${i}.tsv
        done
    )
done