#! /bin/sh
set -e
set -x

export datapath="/data"
export binpath="/install/bin"
export resultpath="${datapath}/results"
export outpath="${datapath}/out"
export iterations=1

# Clean results folder
mkdir -p "${resultpath}"
mkdir -p "${outpath}"
rm "${resultpath}"/* || echo "No results"
rm "${outpath}"/* || echo "No output"

run_all_benchmarks=true
dir="$(dirname "$0")"
# read the options
for var in "$@"
do
    if [ "$var" = "metadata" ];  then
        run_all_benchmarks=false
        $dir/run_metadata
    fi
    if [ "$var" = "pixeldata" ];  then
        run_all_benchmarks=false
        $dir/run_pixeldata
    fi
    if [ "$var" = "tiling" ];  then
        run_all_benchmarks=false
        $dir/run_tiling
    fi
    if [ "$var" = "basic-tiling" ];  then
        run_all_benchmarks=false
        $dir/run_basic_tiling
    fi
done
if [ "$run_all_benchmarks" = "true" ];  then
    $dir/run_metadata
    $dir/run_pixeldata
    $dir/run_tiling
fi